In [1]:
##
## Libraries or Modules
##

import math

math.sqrt(25)

math.pi


3.141592653589793

In [2]:
import math as mt

mt.sqrt(25)

5.0

In [7]:
import numpy
import math
from scipy import stats
from numpy import random

import numpy as np

# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

print (dataOne)

np.mean(dataOne)

[[0.35826603 0.21790792 0.10467283 0.34947316 0.6439449 ]
 [0.90498055 0.31850026 0.14923483 0.48564731 0.71798543]
 [0.91638529 0.38246956 0.36156119 0.42597001 0.6998429 ]
 [0.77012289 0.16408239 0.58357261 0.0698699  0.50983465]
 [0.45669316 0.10428277 0.88886615 0.4375645  0.30503785]]


0.4530707619704136

In [13]:
##
## Functions
##

# Require "def" 
def functionName():
    print('I Love data Science')
    
functionName()

I Love data Science


In [14]:
##
## Variables
##

variableName = 25

variableName1 = 'I Love data Science'

print(variableName1)

I Love data Science


In [20]:
##
## Datatypes
##

variableName = 25
print (type(variableName))

variableName = 25.0
print (type(variableName))

varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

## Require parse Int to String
varOne = 25
varTwo = 'Hello'
varThree = str(varOne) + varTwo
print(varThree)

<class 'int'>
<class 'float'>
50.0
25Hello


In [22]:
##
## Lists and Dictionaries
##

## Lists
listName = [ ]

listOne = [1,2,3,4]

print(listOne[1:3])

## Dictionaries
tel = {'jack': 4098, 'sape': 4139}

tel['jack']

[2, 3]


4098

In [35]:
##
## My Turn
##

import math as mt

dataFamilyAge = { 'father':35, 'mother':33, 'son':10, 'daughter':5, 'grand_mother':60 }

# Return True if x is neither an infinity nor a NaN, and False otherwise
print (mt.isfinite(dataFamilyAge['mother']))

# Return the absolute value of x
print (mt.fabs(dataFamilyAge['son']))

# Return the ceiling of x
print (mt.ceil(dataFamilyAge['daughter']))


True
10.0
5
